services:
  influxdb:
    container_name: influxdb
    image: quay.io/influxdb/influxdb3-core:latest
    ports:
      - 8181:8181
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb/init_influxdb.sh:/docker-entrypoint-initdb.d/init_influxdb.sh 
    command:
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
      - --without-auth
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  influxdb_data:
  grafana_data:
